plugins {
    id "com.android.library"
    id "org.jetbrains.kotlin.android"
    
}

android {
    namespace "com.faceplugin.facesdk_plugin"
    compileSdk 35

    defaultConfig {
        minSdk 24
        // si el plugin trae .so solo para ciertos ABIs:
        ndk {
            abiFilters "arm64-v8a", "armeabi-v7a"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }

    packagingOptions {
        // Evita el crash del strip mientras revisamos .so
        doNotStrip "**/*.so"
    }
}

repositories {
    google()
    mavenCentral()
}

dependencies {
    // Si antes dependas del mdulo local de fotoapparat, cambialo por Maven:
    // implementation project(":libfotoapparat")  // 
    implementation "io.fotoapparat:fotoapparat:2.7.0"
}
